name: TechnoServerMessenger
version: '${project.version}'
main: ru.jadegg2568.jadeservermessenger.ServerMessengerAPI
commands:
  servermessenger:
    description: Server messenger
    usage: /servermessenger help
